version: 0.1.{build}
image: Visual Studio 2019
configuration: Release
build_script:
- ps: dotnet build -c Release
test_script:
- ps: dotnet test -c Release /p:CollectCoverage=true
artifacts:
- path:  '**\*.nupkg'
